# fly.toml
app = "chat-group-socketIO"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["heroku/nodejs"]
  build_command = "pnpm build:fly" 

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = false

[env]
  PORT = "3005"
  NODE_VERSION = "18.x"